/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import FormFirma.FormNovaFirma;
import FormFirma.FormPretragaFirme;
import FormVinarija.FormNovaVinarija;
import FormVinarija.FormPretragaVinarije;

import controller.ClientController;
import domain.Administrator;
import domain.Faktura;
import domain.Firma;
import domain.StavkaFakture;
import domain.Vinarija;
import domain.Vino;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelStavkeFakture;
import session.Session;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame implements Runnable{

    Administrator a;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.a = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani administrator: " + a);
        setTitle("Glavna forma");
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbFirma = new javax.swing.JComboBox();
        txtCenaBezPDV = new javax.swing.JTextField();
        lblPDV = new javax.swing.JLabel();
        txtCenaSaPDV = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnObrisi = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeFakture = new javax.swing.JTable();
        cmbVinarija = new javax.swing.JComboBox();
        cmbVino = new javax.swing.JComboBox();
        txtKolicina = new javax.swing.JTextField();
        txtCenaStavke = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        lblSat = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNovaFirma = new javax.swing.JMenuItem();
        miPretragaFirme = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miNovaVinarija = new javax.swing.JMenuItem();
        miPretragaVinarije = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos fakture"));

        jLabel2.setText("Firma:");

        jLabel3.setText("Cena bez PDV-a:");

        jLabel4.setText("PDV:");

        jLabel5.setText("Cena sa PDV-om:");

        cmbFirma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPDV.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos stavki fakture"));

        jLabel6.setText("Vinarija:");

        jLabel7.setText("Vina izabrane vinarije:");

        jLabel8.setText("Kolicina:");

        jLabel9.setText("Cena:");

        btnObrisi.setText("Obrisi stavku fakture");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj stavku fakture");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        tblStavkeFakture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeFakture);

        cmbVinarija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVinarija.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVinarijaItemStateChanged(evt);
            }
        });

        cmbVino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVinoItemStateChanged(evt);
            }
        });

        txtKolicina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKolicinaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cmbVino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(93, 93, 93)
                                .addComponent(cmbVinarija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(90, 90, 90)
                                .addComponent(txtKolicina))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(104, 104, 104)
                                .addComponent(txtCenaStavke)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbVinarija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbVino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCenaStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisi)
                .addContainerGap())
        );

        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj fakturu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCenaBezPDV)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPDV)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCenaSaPDV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmbFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCenaBezPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblPDV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCenaSaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jMenu6.setText("Firma");

        miNovaFirma.setText("Nova firma");
        miNovaFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaFirmaActionPerformed(evt);
            }
        });
        jMenu6.add(miNovaFirma);

        miPretragaFirme.setText("Pretraga firme");
        miPretragaFirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaFirmeActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaFirme);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Vinarija");

        miNovaVinarija.setText("Nova vinarija");
        miNovaVinarija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaVinarijaActionPerformed(evt);
            }
        });
        jMenu7.add(miNovaVinarija);

        miPretragaVinarije.setText("Pretraga vinarije");
        miPretragaVinarije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaVinarijeActionPerformed(evt);
            }
        });
        jMenu7.add(miPretragaVinarije);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUlogovani)
                            .addComponent(lblSat, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblSat, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUlogovani))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNovaFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaFirmaActionPerformed
        new FormNovaFirma(this, true).setVisible(true);
    }//GEN-LAST:event_miNovaFirmaActionPerformed

    private void miPretragaFirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaFirmeActionPerformed
        new FormPretragaFirme(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaFirmeActionPerformed

    private void miNovaVinarijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaVinarijaActionPerformed
        new FormNovaVinarija(this, true).setVisible(true);
    }//GEN-LAST:event_miNovaVinarijaActionPerformed

    private void miPretragaVinarijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaVinarijeActionPerformed
        new FormPretragaVinarije(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaVinarijeActionPerformed

    private void cmbVinarijaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVinarijaItemStateChanged

        if (cmbVinarija.getSelectedItem() != null) {
            Vinarija v = (Vinarija) cmbVinarija.getSelectedItem();
            popuniVina(v);
        }

    }//GEN-LAST:event_cmbVinarijaItemStateChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if (txtKolicina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti kolicinu!");
            return;
        }

        Vino v = (Vino) cmbVino.getSelectedItem();
        int kolicina = Integer.parseInt(txtKolicina.getText());
        double cenaStavke = Double.parseDouble(txtCenaStavke.getText());

        StavkaFakture sf = new StavkaFakture(null, -1, kolicina, cenaStavke, v);

        TableModelStavkeFakture tm = (TableModelStavkeFakture) tblStavkeFakture.getModel();
        tm.dodajStavku(sf);

        double cenaBezPDV = Double.parseDouble(txtCenaBezPDV.getText());

        txtCenaBezPDV.setText(String.valueOf(cenaBezPDV + sf.getCenaStavke()));

        cenaBezPDV = Double.parseDouble(txtCenaBezPDV.getText());

        txtCenaSaPDV.setText(String.valueOf(cenaBezPDV * (1.2)));

    }//GEN-LAST:event_btnDodajActionPerformed

    private void txtKolicinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKolicinaKeyReleased

        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
                || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {

            if (txtKolicina.getText().isEmpty()) {
                txtCenaStavke.setText("0.00");
                return;
            }

            int kolicina = Integer.parseInt(txtKolicina.getText());

            if (kolicina <= 0) {
                txtKolicina.setText("");
                return;
            }

            Vino v = (Vino) cmbVino.getSelectedItem();

            txtCenaStavke.setText(String.valueOf(v.getCena() * kolicina));

        } else {
            txtKolicina.setText("");
            txtCenaStavke.setText("0.00");
        }

    }//GEN-LAST:event_txtKolicinaKeyReleased

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int row = tblStavkeFakture.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeFakture tm = (TableModelStavkeFakture) tblStavkeFakture.getModel();

            StavkaFakture sf = tm.getStavka(row);

            double cenaBezPDV = Double.parseDouble(txtCenaBezPDV.getText());

            txtCenaBezPDV.setText(String.valueOf(cenaBezPDV - sf.getCenaStavke()));

            cenaBezPDV = Double.parseDouble(txtCenaBezPDV.getText());

            txtCenaSaPDV.setText(String.valueOf(cenaBezPDV * (1.2)));

            tm.obrisiStavku(row);
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void cmbVinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVinoItemStateChanged

        if (cmbVino.getSelectedItem() != null) {
            if (txtKolicina.getText().isEmpty()) {
                txtCenaStavke.setText("0.00");
                return;
            }

            int kolicina = Integer.parseInt(txtKolicina.getText());

            if (kolicina <= 0) {
                txtKolicina.setText("");
                return;
            }

            Vino v = (Vino) cmbVino.getSelectedItem();

            txtCenaStavke.setText(String.valueOf(v.getCena() * kolicina));
        }

    }//GEN-LAST:event_cmbVinoItemStateChanged

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            Firma firma = (Firma) cmbFirma.getSelectedItem();
            double cenaBezPDV = Double.parseDouble(txtCenaBezPDV.getText());
            double cenaSaPDV = Double.parseDouble(txtCenaSaPDV.getText());

            TableModelStavkeFakture tm = (TableModelStavkeFakture) tblStavkeFakture.getModel();

            Faktura f = new Faktura(null, new Date(), cenaBezPDV, 20,
                    cenaSaPDV, firma, a, tm.getLista());

            ClientController.getInstance().addFaktura(f);
            resetujFormu();
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana faktura!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se izlogujete?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbFirma;
    private javax.swing.JComboBox cmbVinarija;
    private javax.swing.JComboBox cmbVino;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPDV;
    private javax.swing.JLabel lblSat;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNovaFirma;
    private javax.swing.JMenuItem miNovaVinarija;
    private javax.swing.JMenuItem miPretragaFirme;
    private javax.swing.JMenuItem miPretragaVinarije;
    private javax.swing.JTable tblStavkeFakture;
    private javax.swing.JTextField txtCenaBezPDV;
    private javax.swing.JTextField txtCenaSaPDV;
    private javax.swing.JTextField txtCenaStavke;
    private javax.swing.JTextField txtKolicina;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        popuniFirme();
        popuniVinarije();
        txtCenaStavke.setEnabled(false);
        txtCenaSaPDV.setEnabled(false);
        txtCenaBezPDV.setEnabled(false);
        txtCenaStavke.setText("0.00");
        txtCenaSaPDV.setText("0.00");
        txtCenaBezPDV.setText("0.00");
        lblPDV.setText("20%");
        tblStavkeFakture.setModel(new TableModelStavkeFakture());
        Thread th = new Thread(this);
        th.start();
    }

    public void popuniFirme() {
        try {
            ArrayList<Firma> firme = ClientController.getInstance().getAllFirma();

            cmbFirma.removeAllItems();

            for (Firma firma : firme) {
                cmbFirma.addItem(firma);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniVinarije() {
        try {
            ArrayList<Vinarija> vinarije = ClientController.getInstance().getAllVinarija();

            cmbVinarija.removeAllItems();

            for (Vinarija vinarija : vinarije) {
                cmbVinarija.addItem(vinarija);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniVina(Vinarija v) {
        try {
            ArrayList<Vino> listaVina = ClientController.getInstance().getAllVino(v);

            cmbVino.removeAllItems();

            for (Vino vino : listaVina) {
                cmbVino.addItem(vino);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetujFormu() {
        TableModelStavkeFakture tm = (TableModelStavkeFakture) tblStavkeFakture.getModel();
        tm.isprazniTabelu();
        txtCenaStavke.setText("0.00");
        txtCenaSaPDV.setText("0.00");
        txtCenaBezPDV.setText("0.00");
        txtKolicina.setText("");
    }

    @Override
    public void run() {
        while(true){
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            lblSat.setText("Datum i vreme: " + sdf.format(new Date()));
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
